### ISSUE TITLE
Revamp UI

### ISSUE THREAD

**Issue by nullity00** [nullity00/Proxies-website#1]
## https://proxies.yacademy.dev/
![WhatsApp Image 2024-02-22 at 01 35 53_e70dffe7](https://github.com/nullity00/Proxies-website/assets/70228821/9e335f12-7386-4666-ab07-d3fc7847e156)
![image](https://github.com/nullity00/Proxies-website/assets/70228821/33430426-c0fd-4a21-80a1-48380faa0a55)

## TODO
- [ ] Change the logo, get the logo from here : https://github.com/nullity00/zacademy-site/blob/main/src/public/logo.svg
- [ ] Change the favicon, get it here : https://github.com/nullity00/zacademy-site/blob/main/src/public/favicon.ico
- [ ] Maintain the same amount of margin on the left & right as here : https://effortless-crepe-67200a.netlify.app/
- [ ] Use the font family mentioned here : https://github.com/nullity00/zacademy-site/blob/main/tailwind.config.cjs#L18
- [ ] Use the text color used here : https://github.com/nullity00/zacademy-site/blob/main/tailwind.config.cjs#L12
- [ ] Remove those extra lines & make the search bar prettier + the logo has to be in the middle 
- [ ] - The left bar has to be well spaced

**Comment by nullity00** [comment]
Closed by #2
